name: Nightly Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build binaries
        run: |
          mkdir -p dist
          BIN_NAME="hej-${{ matrix.goos }}-${{ matrix.goarch }}-nightly"
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
            go build -ldflags="-s -w" -o dist/$BIN_NAME hej.go

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hej-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Flatten dist directory
        run: |
          mkdir flat-dist
          find dist -type f -exec mv {} flat-dist/ \;
          ls -lh flat-dist

      - name: Set nightly tag
        id: vars
        run: |
          DATE=$(date +'%Y%m%d-%H%M')
          echo "TAG=nightly-$DATE" >> $GITHUB_ENV
          echo "TITLE=Nightly Build $DATE" >> $GITHUB_ENV

      - name: Publish nightly release
        run: |
          gh release create "$TAG" flat-dist/* \
            --title "$TITLE" \
            --notes "Automated nightly build from main branch ($TAG)." \
            --prerelease

        env:
          GH_TOKEN: ${{ github.token }}