name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build binaries
        run: |
          mkdir -p dist
          BIN_NAME="clihelp-${{ matrix.goos }}-${{ matrix.goarch }}"
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
            go build -ldflags="-s -w" -o dist/$BIN_NAME clihelp.go

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: clihelp-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Publish release
        run: |
          gh release create "${GITHUB_REF_NAME}" dist/** \
            --title "Release ${GITHUB_REF_NAME}" \
            --notes "Automated release for ${GITHUB_REF_NAME}" \
            --latest
        env:
          GH_TOKEN: ${{ github.token }}
