name: Build and Release

on:
  push:
    tags:
      - 'v*'   # Trigger only when you push a version tag like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
            go build -ldflags="-s -w" -o dist/clihelp-${{ matrix.goos }}-${{ matrix.goarch }} clihelp.go

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
